project_id = "iffvjtfrqaesoehbwtgi"

[functions.google-auth]
verify_jwt = false

[functions.google-drive-list]
verify_jwt = false

[functions.google-drive-download]
verify_jwt = false

[functions.google-drive-organize]
verify_jwt = false

[functions.google-drive-rename]
verify_jwt = false

[functions.video-metadata-extractor]
verify_jwt = false

[functions.project-file-generator]
verify_jwt = false

[functions.google-drive-upload]
verify_jwt = false

[functions.google-vision-video-analysis]
verify_jwt = false

[functions.video-metadata-deep-extract]
verify_jwt = false